version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gradle"
    directory: "/cdk"
    schedule:
      interval: "monthly"
