/*
 * This source file was generated by the Gradle 'init' task
 */
package com.renaghan.todo.app;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    TodoApp classUnderTest = new TodoApp();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
