management:
  endpoint:
    health:
      # show all on actuator info page
      show-details: always
      show-components: always
  endpoints:
    web:
      # custom actuator base path
      base-path: "/mgmt"
      exposure:
        # enable all actuator paths
        include: "*"
    jackson:
      # use common mapper so we can pretty-print
      isolated-object-mapper: false
  health:
    jms:
      # don't verify the health of the JMS broker
      enabled: false
  metrics:
    tags:
      environment: ${ENVIRONMENT_NAME}

server:
  compression:
    # gzip compression for http responses
    enabled: true
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-path: always
    include-stacktrace: always
  forward-headers-strategy: framework

spring:
  application:
    name: todo-app
  cloud:
    aws:
      region:
        static: us-east-2
      sns:
        enabled: false
  jackson:
    serialization:
      # pretty-print json
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  main:
    banner-mode: off

# configuration of error-handling-spring-boot-starter (https://wimdeblauwe.github.io/error-handling-spring-boot-starter/)
error:
  handling:
    # noinspection SpringBootApplicationYaml
    exception-logging: WITH_STACKTRACE

custom:
  invitation-codes: 11542
  sharing-queue: ${ENVIRONMENT_NAME}-todo-app-todo-sharing-queue
  external-url: https://${ENVIRONMENT_NAME}.todo-app.renaghan.net
  auto-confirm-collaborations: false
  confirm-email-from-address: noreply@renaghan.com
  environment: ${ENVIRONMENT_NAME}