spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-name: todo-app-client
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          cognito:
            issuer-uri: ${COGNITO_PROVIDER_URL}
  activemq:
    broker-url: ${WEB_SOCKET_RELAY_ENDPOINT}
    user: ${WEB_SOCKET_RELAY_USERNAME}
    password: ${WEB_SOCKET_RELAY_PASSWORD}

management:
  cloudwatch:
    metrics:
      export:
        enabled: false

# noinspection SpringBootApplicationYaml
custom:
  use-cognito-as-identity-provider: true
  auto-confirm-collaborations: false
  web-socket-relay-use-ssl: true
  provide-test-todo-controller: false
