/*
 * This source file was generated by the Gradle 'init' task
 */
package com.renaghan.todo.cdk;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class InfraTest {
  @Test
  void appHasAGreeting() {
    Infra classUnderTest = new Infra();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
